create table if not exists "AspNetRoles"
(
    "Id"               bigint generated by default as identity,
    "Name"             varchar(256),
    "NormalizedName"   varchar(256),
    "ConcurrencyStamp" text,
    constraint "PK_AspNetRoles"
        primary key ("Id")
);

create unique index if not exists "RoleNameIndex"
    on "AspNetRoles" ("NormalizedName");

create table if not exists "AspNetUsers"
(
    "Id"                   bigint generated by default as identity,
    "FirstName"            text    not null,
    "LastName"             text    not null,
    "UserName"             varchar(256),
    "NormalizedUserName"   varchar(256),
    "Email"                varchar(256),
    "NormalizedEmail"      varchar(256),
    "EmailConfirmed"       boolean not null,
    "PasswordHash"         text,
    "SecurityStamp"        text,
    "ConcurrencyStamp"     text,
    "PhoneNumber"          text,
    "PhoneNumberConfirmed" boolean not null,
    "TwoFactorEnabled"     boolean not null,
    "LockoutEnd"           timestamp with time zone,
    "LockoutEnabled"       boolean not null,
    "AccessFailedCount"    integer not null,
    constraint "PK_AspNetUsers"
        primary key ("Id")
);

create index if not exists "EmailIndex"
    on "AspNetUsers" ("NormalizedEmail");

create unique index if not exists "UserNameIndex"
    on "AspNetUsers" ("NormalizedUserName");

create table if not exists "AspNetRoleClaims"
(
    "Id"         integer generated by default as identity,
    "RoleId"     bigint not null,
    "ClaimType"  text,
    "ClaimValue" text,
    constraint "PK_AspNetRoleClaims"
        primary key ("Id"),
    constraint "FK_AspNetRoleClaims_AspNetRoles_RoleId"
        foreign key ("RoleId") references "AspNetRoles"
            on delete cascade
);

create index if not exists "IX_AspNetRoleClaims_RoleId"
    on "AspNetRoleClaims" ("RoleId");

create table if not exists "AspNetUserClaims"
(
    "Id"         integer generated by default as identity,
    "UserId"     bigint not null,
    "ClaimType"  text,
    "ClaimValue" text,
    constraint "PK_AspNetUserClaims"
        primary key ("Id"),
    constraint "FK_AspNetUserClaims_AspNetUsers_UserId"
        foreign key ("UserId") references "AspNetUsers"
            on delete cascade
);

create index if not exists "IX_AspNetUserClaims_UserId"
    on "AspNetUserClaims" ("UserId");

create table if not exists "AspNetUserLogins"
(
    "LoginProvider"       varchar(128) not null,
    "ProviderKey"         varchar(128) not null,
    "ProviderDisplayName" text,
    "UserId"              bigint       not null,
    constraint "PK_AspNetUserLogins"
        primary key ("LoginProvider", "ProviderKey"),
    constraint "FK_AspNetUserLogins_AspNetUsers_UserId"
        foreign key ("UserId") references "AspNetUsers"
            on delete cascade
);

create index if not exists "IX_AspNetUserLogins_UserId"
    on "AspNetUserLogins" ("UserId");

create table if not exists "AspNetUserRoles"
(
    "UserId" bigint not null,
    "RoleId" bigint not null,
    constraint "PK_AspNetUserRoles"
        primary key ("UserId", "RoleId"),
    constraint "FK_AspNetUserRoles_AspNetRoles_RoleId"
        foreign key ("RoleId") references "AspNetRoles"
            on delete cascade,
    constraint "FK_AspNetUserRoles_AspNetUsers_UserId"
        foreign key ("UserId") references "AspNetUsers"
            on delete cascade
);

create index if not exists "IX_AspNetUserRoles_RoleId"
    on "AspNetUserRoles" ("RoleId");

create table if not exists "AspNetUserTokens"
(
    "UserId"        bigint       not null,
    "LoginProvider" varchar(128) not null,
    "Name"          varchar(128) not null,
    "Value"         text,
    constraint "PK_AspNetUserTokens"
        primary key ("UserId", "LoginProvider", "Name"),
    constraint "FK_AspNetUserTokens_AspNetUsers_UserId"
        foreign key ("UserId") references "AspNetUsers"
            on delete cascade
);