services:
  
#  traefik:
  
  brand_and_product_db:
    container_name: brand_and_product_db
    build:
        context: .
        dockerfile: Databases/BrandsAndProductsDatabase/Dockerfile
    restart: on-failure
    ports: 
      - "5432:5432"
    
  brand_and_product_api:
    container_name: brand_and_product_api
    build:
        context: .
        dockerfile: BrandAndProductDatabase.API/Dockerfile
    restart: on-failure
    ports:
      - "8081:80"
  
  product_data_retriever_api:
    container_name: product_data_retriever_api
    build:
        context: .
        dockerfile: FairWearProductDataRetriever.API/Dockerfile
    restart: on-failure
    ports:
      - "8082:80"