services:
  
#  traefik:
  
  brand_and_product_db:
    container_name: brand_and_product_db
    build:
        context: .
        dockerfile: Databases/BrandsAndProductsDatabase/Dockerfile
    restart: on-failure
    ports: 
      - "5432:5432"
    
  gateway_api:
    container_name: gateway_api
    build:
        context: .
        dockerfile: FairWearGateway.API/Dockerfile
    restart: on-failure
    ports:
      - "8080:80"  
    
  brand_and_product_api:
    container_name: brand_and_product_api
    build:
        context: .
        dockerfile: BrandAndProductDatabase.API/Dockerfile
    restart: on-failure
    ports:
      - "8081:80"
  
  product_data_retriever_api:
    container_name: product_data_retriever_api
    build:
        context: .
        dockerfile: FairWearProductDataRetriever.API/Dockerfile
    restart: on-failure
    ports:
      - "8082:80"
  
  good_on_you_scrapper_api:
    container_name: good_on_you_scrapper_api
    build:
      context: .
      dockerfile: GoodOnYouScrapper.API/Dockerfile
    restart: on-failure
    ports:
      - "8083:80"