name: Authentication Database CD

on:
  push:
    branches:
      - master
      - develop
      - release/*
    paths:
      - 'Databases/AuthenticationDatabase/**'
      - '.github/workflows/AuthenticationDatabase.yml'

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Retrieve GITHUB_REF
        id: get_branch
        env:
          BRANCH: ${{ github.ref_name }}
        run: echo "tag=${BRANCH//\//_}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Databases/AuthenticationDatabase/Dockerfile
          push: true
          tags: |
            ${{ secrets.REGISTRY_URL }}/fairwear/authentication_db:${{ steps.get_branch.outputs.tag }}-${{ github.run_number }}
            ${{ secrets.REGISTRY_URL }}/fairwear/authentication_db:latest

      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          title: "Deliver Authentication Database to Registry"
          username: GitHub Actions
          avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
        