name: Back Office CI/CD

on:
  push:
    branches:
      - master
      - develop
      - feature/*
      - hotfix/*
      - release/*
      - fix/*
    paths:
      - 'BackOffice/**'
      - '.github/workflows/BackOffice.yml'
      - 'Scripts/**'

jobs: 
  linter:
    name: 'Linter'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'

      - name: Cache Resharper CLI
        id: cache-resharper
        uses: actions/cache@v4
        with:
          path: ~/.dotnet/tools
          key: resharper-cli
          restore-keys: resharper-cli
        
      - name: Install Resharper CLI
        if: steps.cache-resharper.outputs.cache-hit != 'true'
        run: |
          dotnet tool install JetBrains.ReSharper.GlobalTools --tool-path ~/.dotnet/tools --version 2023.3.0
          export PATH=$PATH:~/.dotnet/tools
          
      - name: Run ReSharper InspectCode
        run: jb inspectcode BackOffice/BackOffice.csproj -o=resharper-report.xml -f=Xml -verbosity=INFO -no-swea

      - name: Check Resharper results
        run: |
          if grep -q 'Severity="WARNING"' resharper-report.xml; then cat resharper-report.xml && exit 1; fi
          if grep -q 'Severity="ERROR"' resharper-report.xml; then cat resharper-report.xml && exit 1; fi

      - uses: sarisia/actions-status-discord@v1
        if: always() && (job.status == 'failure' || job.status == 'cancelled')
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          title: "Linter on Back Office"
          username: GitHub Actions
          avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          
  build:
    name: 'Build'
    needs: linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core SDK 7.0.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-back-office-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-back-office-

      - name: 'Install dependencies'
        run: dotnet restore BackOffice/BackOffice.csproj

      - name: Build
        run: dotnet build BackOffice/BackOffice.csproj --configuration Release --no-restore

      - uses: sarisia/actions-status-discord@v1
        if: always() && (job.status == 'failure' || job.status == 'cancelled')
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          title: "Build & Test Back Office"
          username: GitHub Actions
          avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
        
  deploy:
    name: 'Deploy'
    needs:
      - linter
      - build
    runs-on: ubuntu-latest
    if: contains(github.ref, 'release') || contains(github.ref, 'develop') || contains(github.ref, 'master')
    steps:
      - uses: actions/checkout@v4

      - name: Retrieve GITHUB_REF
        id: get_branch
        env:
          BRANCH: ${{ github.ref_name }}
        run: echo "tag=${BRANCH//\//_}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: BackOffice/Dockerfile
          push: true
          tags: |
            ${{ secrets.REGISTRY_URL }}/fairwear_back_office:${{ steps.get_branch.outputs.tag }}-${{ github.run_number }}
            ${{ secrets.REGISTRY_URL }}/fairwear_back_office:latest
            
      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          title: "Deliver Back Office to Registry"
          username: GitHub Actions
          avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png