  name: Brand & Product Database CD
  
  on:
    push:
      branches:
        - master
        - develop
        - release/*
      paths:
        - 'Databases/BrandsAndProductsDatabase/**'
        - '.github/workflows/BrandAndProductDatabase.yml'

  jobs:
    deploy:
      name: 'Deploy'
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - name: Retrieve GITHUB_REF
          id: get_branch
          env:
            BRANCH: ${{ github.ref_name }}
          run: echo "::set-output name=tag::${BRANCH//\//_}"
          
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Login to Docker Registry
          uses: docker/login-action@v2
          with:
            registry: https://registry.leedrisdev.com
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Build and push
          uses: docker/build-push-action@v4
          with:
            context: .
            file: ./GoodOnYouScrapper.Service/Dockerfile
            push: true
            tags: |
              registry.leedrisdev.com/fairwear_brand_and_product_db:${{ steps.get_branch.outputs.tag }}-${{ github.run_number }}
              registry.leedrisdev.com/fairwear_brand_and_product_db:latest
              
        - uses: sarisia/actions-status-discord@v1
          if: always()
          with:
            webhook: ${{ secrets.DISCORD_WEBHOOK }}
            status: ${{ job.status }}
            title: "Deliver Brand and Product Database to Registry"
            username: GitHub Actions
            avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
        