name: GoodOnYou Scrapper API CI

on:
  push:
    branches:
      - master
      - develop
      - feature/*
      - hotfix/*
      - release/*
      - fix/*
    paths:
      - 'GoodOnYouScrapper.API/**'
      - 'GoodOnYouScrapper.API.Tests/**'
      - '.github/workflows/GoodOnYouScrapperAPI_CI.yml'
      - 'Scripts/**'

jobs:

  linter:
    name: 'Linter'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core SDK 7.0.x
        uses: actions/setup-dotnet@v3
        with:
            dotnet-version: '7.0.x'
      
      - name: Cache Resharper CLI
        id: cache-resharper
        uses: actions/cache@v3
        with:
          path: ~/.dotnet/tools
          key: resharper-cli
          restore-keys: resharper-cli
      
      - name: Install Resharper CLI
        if: steps.cache-resharper.outputs.cache-hit != 'true'
        run: |
          dotnet tool install JetBrains.ReSharper.GlobalTools --tool-path ~/.dotnet/tools
          export PATH=$PATH:~/.dotnet/tools

      - name: Run ReSharper InspectCode
        run: jb inspectcode GoodOnYouScrapper.API/GoodOnYouScrapper.API.csproj -o=resharper-report.xml -f=Xml -verbosity=INFO -no-swea

      - name: Check Resharper results
        run: |
          if grep -q 'Severity="WARNING"' resharper-report.xml; then cat resharper-report.xml && exit 1; fi
          if grep -q 'Severity="ERROR"' resharper-report.xml; then cat resharper-report.xml && exit 1; fi
          if grep -q 'Severity="SUGGESTION"' resharper-report.xml; then cat resharper-report.xml && exit 1; fi

      - uses: sarisia/actions-status-discord@v1
        if: always() && (job.status == 'failure' || job.status == 'cancelled')
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          title: "Linter on GoodOnYou Scrapper API"
          username: GitHub Actions
          avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png

  
  build:
    name: 'Build'
    needs: linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core SDK 7.0.x
        uses: actions/setup-dotnet@v3
        with:
            dotnet-version: '7.0.x'

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-goodonyou-scrapper-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-goodonyou-scrapper-

      - name: 'Install dependencies'
        run: dotnet restore ./GoodOnYouScrapper.API/GoodOnYouScrapper.API.csproj
        
      - name: Build
        run: dotnet build ./GoodOnYouScrapper.API/GoodOnYouScrapper.API.csproj --configuration Release --no-restore 
      
      - uses: sarisia/actions-status-discord@v1
        if: always() && (job.status == 'failure' || job.status == 'cancelled')
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          title: "Build & Test GoodOnYou Scrapper API"
          username: GitHub Actions
          avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
  
  test:
    name: 'Tests'
    needs: 
      - build
      - linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core SDK 7.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-goodonyou-scrapper-tests-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-goodonyou-scrapper-tests-

      - name: 'Install dependencies'
        run: |
          dotnet restore ./GoodOnYouScrapper.API.Tests/GoodOnYouScrapper.API.Tests.csproj
          dotnet restore ./GoodOnYouScrapper.API/GoodOnYouScrapper.API.csproj  
          
      - name: 'Run tests'
        run: dotnet test --no-restore  --verbosity normal GoodOnYouScrapper.API.Tests/GoodOnYouScrapper.API.Tests.csproj
          
      - name: 'Code Coverage'
        run: ./Scripts/code-coverage-ci.sh -p GoodOnYouScrapper.API.Tests/GoodOnYouScrapper.API.Tests.csproj -t 79
      
      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          title: "Build & Test GoodOnYou Scrapper API"
          username: GitHub Actions
          avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
  
  deploy:
    name: 'Deploy'
    needs:
      - linter
      - build
      - test
    runs-on: ubuntu-latest
#    if: contains(github.ref, 'release')
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: https://docker-registry.leedrisdev.engineer
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./GoodOnYouScrapper.API/Dockerfile
          push: true
          tags: https://docker-registry.leedrisdev.engineer/goodonyou_scrapper_api:release-${{ github.run_number }}