name: GoodOnYou Scrapper API CI

on:
  push:
    branches:
      - master
      - develop
      - feature/*
      - hotfix/*
      - release/*
    paths:
      - 'GoodOnYouScrapperAPI/**'
      - 'GoodOnYouScrapperAPI.Tests/**'
      - '.github/workflows/GoodOnYouScrapperAPI_CI.yml'

jobs:

  linter:
    name: 'Linter'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core SDK 7.0.x
        uses: actions/setup-dotnet@v3
        with:
            dotnet-version: '7.0.x'
      
      - name: Cache Resharper CLI
        id: cache-resharper
        uses: actions/cache@v2
        with:
          path: ~/.dotnet/tools
          key: resharper-cli
          restore-keys: resharper-cli
      
      - name: Install Resharper CLI
        if: steps.cache-resharper.outputs.cache-hit != 'true'
        run: |
          dotnet tool install JetBrains.ReSharper.GlobalTools --tool-path ~/.dotnet/tools
          export PATH=$PATH:~/.dotnet/tools

      - name: Run ReSharper InspectCode
        run: jb inspectcode GoodOnYouScrapperAPI/GoodOnYouScrapperAPI.csproj -o=resharper-report.txt -f:Text -verbosity=INFO -no-swea

      - name: Check Resharper results
        run: |
          if grep -q "<ReportInspectionResults>" resharper-results.txt; then
            echo "Resharper detected issues in the code."
            exit 1
          else
            echo "Code is clean according to Resharper."
          fi

      - name: Upload ReSharper Report
        uses: actions/upload-artifact@v3
        with:
          name: resharper-report
          path: resharper-report.txt

      - uses: sarisia/actions-status-discord@v1
        if: ${{ job.status == 'failure' || job.status == 'cancelled' }}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          title: "Linter on GoodOnYou Scrapper API"
          username: GitHub Actions
          avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png

  
  build:
    name: 'Build'
    needs: linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core SDK 7.0.x
        uses: actions/setup-dotnet@v3
        with:
            dotnet-version: '7.0.x'

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: 'Install dependencies'
        run: dotnet restore ./GoodOnYouScrapperAPI/GoodOnYouScrapperAPI.csproj
        
      - name: Build
        run: dotnet build ./GoodOnYouScrapperAPI/GoodOnYouScrapperAPI.csproj --configuration Release --no-restore 
      
      - uses: sarisia/actions-status-discord@v1
        if: ${{ job.status == 'failure' || job.status == 'cancelled' }}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          title: "Build & Test GoodOnYou Scrapper API"
          username: GitHub Actions
          avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
  
  test:
    name: 'Tests'
    needs: 
      - build
      - linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core SDK 7.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: 'Install dependencies'
        run: |
          dotnet restore ./GoodOnYouScrapperAPI.Tests/GoodOnYouScrapperAPI.Tests.csproj
          dotnet restore ./GoodOnYouScrapperAPI/GoodOnYouScrapperAPI.csproj  
          
      - name: 'DotNet Test'
        run: dotnet test --no-restore --verbosity normal GoodOnYouScrapperAPI.Tests/GoodOnYouScrapperAPI.Tests.csproj

      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          title: "Build & Test GoodOnYou Scrapper API"
          username: GitHub Actions
          avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          