name: Users Database CD

on:
  push:
    branches:
      - master
      - develop
      - release/*
    paths:
      - 'Databases/UsersDatabase/**'
      - '.github/workflows/UsersDatabase.yml'

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Retrieve GITHUB_REF
        id: get_branch
        env:
          BRANCH: ${{ github.ref_name }}
        run: echo "::set-output name=tag::${BRANCH//\//_}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Databases/UsersDatabase/Dockerfile
          push: true
          tags: |
            registry.digitalocean.com/fairwear/users_db:${{ steps.get_branch.outputs.tag }}-${{ github.run_number }}
            registry.digitalocean.com/fairwear/users_db:latest

      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          title: "Deliver Users Database to Registry"
          username: GitHub Actions
          avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
        